spring.application.name=auth-service

#Data Source Properties
spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=123456

#ORM Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Auth Service
# Changed from 8080 to 8081 to avoid port conflict
server.port=8081
server.ssl.enabled=false
server.tomcat.native=false

jwt.secretKey=Zr7vE5tH9XcV2m9s0P6u7xG5XkZ9f4m2wEJ3QnR8o9s=
jwt.resetExpiryMinutes=10
jwt.expiryMinutes=10
jwt.secretKeyExpiryInterval=60

# SMTP Mail Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=verma6858@gmail.com
spring.mail.password=qfpn ivwz lwtz qvob
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Disable Spring Cloud / Boot compatibility check
spring.cloud.compatibility-verifier.enabled=false
