spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.rv.notification.event.OrderEvent
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: verma6858@gmail.com
    password: qfpn ivwz lwtz qvob
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8084
notification:
  email:
    subject: "We received your SwiftCart order - ${orderTrackingNum}"
    template: "Hi, your order ${orderTrackingNum} is confirmed. Thank you for shopping with us!"  
