spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/swiftcart_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: verma6858@gmail.com
    password: qfpn ivwz lwtz qvob
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081
  ssl:
    enabled: false
  tomcat:
    native: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
jwt:
  secret: 2b7e151628aed2a6abf7158809cf4f3c2b7e151628aed2a6abf7158809cf4f3c
  expiration: 900000
