server:
  port: 8079
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: product-listing-service
          uri: lb://product-listing-service
          predicates:
            - Path=/api/products/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
            - Path=/api/v1/cart/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**

        - id: campaign-service
          uri: lb://campaign-service
          predicates:
            - Path=/api/v1/campaigns/**

        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/v1/support/**

      default-filters:
        - name: CircuitBreaker
          args:
            name: gatewayCB
            fallbackUri: forward:/fallback

resilience4j:
  circuitbreaker:
    instances:
      gatewayCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# JWT properties
jwt:
  secret: 2b7e151628aed2a6abf7158809cf4f3c2b7e151628aed2a6abf7158809cf4f3c
  expiration: 900000
